# Setup
title:               खुल्ला डाटा पुस्तिका
tagline:             'Open Knowledge Nepal'
description:         'खुल्ला डाटा पुस्तिका'
url:                 http://127.0.0.1:4000
baseurl:             '/opendatahandbook'
paginate:            5

# About/contact
author:
  name:              Open Knowledge Nepal - Project
  url:               https://twitter.com/okfn_np/
  email:             openknowledgenepal@gmail.com

# Custom vars
version:             1.1 | First Edition 
github:
  repo:              https://github.com/okfnepal/opendatahandbook-nepali