# Setup
title:               खुल्ला डाटा पुस्तिका
tagline:             'Open Knowledge Nepal'
description:         'खुल्ला डाटा पुस्तिका'
url:                 https://okfnepal.github.io/opendatahandbook-nepali/
baseurl:             'https://okfnepal.github.io/opendatahandbook-nepali/'
paginate:            5

# About/contact
author:
  name:              Open Knowledge Nepal - Project
  url:               https://twitter.com/okfn_np/
  email:             openknowledgenepal@gmail.com

# Custom vars
version:             1.1 | First Edition 
github:
  repo:              https://github.com/okfnepal/opendatahandbook-nepali